### ISSUE TITLE
客户端连接上就报错了

### ISSUE THREAD

**Issue by jackjieYYY** [Ehco1996/aioshadowsocks#10]
docker 版本没问题 但是普通版客户端连接上就报错了

![TIM图片20191022025952](https://user-images.githubusercontent.com/53422254/67221964-12ca2000-f478-11e9-8a2b-f88205f07f2e.png)

vultr的centos小鸡

yum install -y wget
yum install -y python3-devel
yum install -y git
systemctl stop firewalld.service
systemctl disable firewalld.service 
export SS_API_ENDPOINT="http://防偷窥/api/user_ss_config/1/?token=admin"
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
git clone https://github.com/Ehco1996/aioshadowsocks.git
cd aioshadowsocks
pip3 install -r requirements.txt
python3 server.py

**Comment by Ehco1996** [comment]
Python需要3.7以上的版本
