### ISSUE TITLE
服务器最小资源请求

### ISSUE THREAD

**Issue by Okeyja** [Ehco1996/aioshadowsocks#104]
请问服务器的最小资源请求是多少？

chacha20-ietf-poly1305 可能 1C 512M 的带不动，但是可以启动，几个小时后就把整个服务器搞垮。

作者大大可以排查一下是不是有内存泄漏。

**Comment by Ehco1996** [comment]
@Okeyja  不好意思刚看到，内存泄露请问是咋观察到的？我自己有一个一直在跑 好几个月了，没发现有内存泄露的问题

**Comment by Okeyja** [comment]
可能是我这边机器带不动libsodium吧。换aes-256-gcm了过后就没有down过。

**Comment by Okeyja** [comment]
具体没有打印的Log出来，没有办法tracing。

**Comment by Ehco1996** [comment]
@Okeyja ss本身是带prom监控的哦，可以考虑接一套试试
