### ISSUE TITLE
支持所有加密方法吗？

### ISSUE THREAD

**Issue by amcloudme** [Ehco1996/aioshadowsocks#11]
支持所有加密方法吗？

保持官方更新吗？

**Comment by jokerase** [comment]
我也想知道

**Comment by Ehco1996** [comment]
目前只支持aes系列加密

最近比较忙没空写加密相关的东西，但是框架都搭好了，欢迎pr

**Comment by perfect-network** [comment]
> 目前只支持aes系列加密
> 
> 最近比较忙没空写加密相关的东西，但是框架都搭好了，欢迎pr

不会GO  没办法做pr

**Comment by Ehco1996** [comment]
已经支持了所有可靠的aead加密方法
