### ISSUE TITLE
现在翻不出去了？还是怎么回事？（2021/1/18）出现 <class 'asyncio.exceptions.TimeoutError'> 

### ISSUE THREAD

**Issue by yscxyjd** [Ehco1996/aioshadowsocks#125]
一切正常配置面板并且成功启动，手机也正确链接上节点，但是好像翻不出，在同一台服务器上搭建的shadowsocks可以正常过墙。
主要出现的错误就是`aioshadowsocks | [WARNING]2021-01-18 03:22:55,184 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: play.googleapis.com:443
`
能及时告知一下是怎么回事吗，最近研究你的项目几天了，对你的项目也有大致的了解了。

**Comment by PuckTeam** [comment]
![image](https://user-images.githubusercontent.com/49980280/104869202-63cd0a80-5980-11eb-8dd4-df1b0d9c04b6.png)

**Comment by PuckTeam** [comment]
@Ehco1996

**Comment by Ehco1996** [comment]
看上去是你的节点本身不能访问 play.googleapis.com:443 这个网址，超时了

**Comment by yscxyjd** [comment]
可是我用shadowsocks搭建的所有网站都可以访问，用aioshadowsocks搭建的所有的都不可以访问

**Comment by yscxyjd** [comment]
可是我用shadowsocks搭建的所有网站都可以访问，用aioshadowsocks搭建的所有的国外都不可以访问，国内正常.
@Ehco1996

**Comment by Ehco1996** [comment]
那可能是timeout时间设置的太短了 https://github.com/Ehco1996/aioshadowsocks/blob/2e26db99a27e230866fca30622bc4795d2720caf/shadowsocks/core.py#L138 可以把这行的`await asyncio.wait_for(task, 5)`中的5改成30再试试

**Comment by yscxyjd** [comment]
`[root@hwsrv-825895 aioshadowsocks]# docker-compose up
Creating aioshadowsocks ... done
Creating ehco ... 
Attaching to ehco, aioshadowsocks
ehco    | {"level":"info","ts":1610941590.958601,"caller":"relay/log.go:10","msg":"Init zap logger"}
ehco    | {"level":"info","ts":1610941590.959208,"caller":"relay/relay.go:87","msg":"start relay AT: 0.0.0.0:1234 Over: raw TO: 0.0.0.0:9001 Through raw"}
aioshadowsocks | [INFO]2021-01-18 03:46:32,145 _init_memory_db line:81 正在创建<Model: User>内存数据库
aioshadowsocks | [INFO]2021-01-18 03:46:33,651 _start_metrics_server line:139 Start Metrics Server At: http://0.0.0.0:9888/metrics
aioshadowsocks | [INFO]2021-01-18 03:46:33,651 init_server line:59 user:1 method:aes-256-gcm password:baXZ4VXnBVs5 0.0.0.0:1025 已启动
aioshadowsocks | [INFO]2021-01-18 03:46:33,652 init_server line:59 user:2 method:aes-256-gcm password:R7MDoyDmLDjc 0.0.0.0:1026 已启动
aioshadowsocks | [INFO]2021-01-18 03:46:33,653 init_server line:59 user:3 method:aes-256-gcm password:vriaO0Ep2Ky3 0.0.0.0:1027 已启动
aioshadowsocks | [INFO]2021-01-18 03:46:33,654 init_server line:59 user:5 method:aes-256-gcm password:hzWgf0ApZuH5 0.0.0.0:1029 已启动
aioshadowsocks | [INFO]2021-01-18 03:47:39,610 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:47:40,407 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:47:44,905 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:47:44,911 _handle_stage_init line:125 parse_header_success domain dst:clientservices.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:47:46,183 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:47:46,188 _handle_stage_init line:125 parse_header_success domain dst:content-autofill.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:47:49,918 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: clientservices.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:47:50,569 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:47:50,573 _handle_stage_init line:125 parse_header_success domain dst:clientservices.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:47:51,191 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: content-autofill.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:47:51,705 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:47:51,715 _handle_stage_init line:125 parse_header_success domain dst:content-autofill.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:47:51,717 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:47:51,722 _handle_stage_init line:125 parse_header_success domain dst:growth-pa.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:47:54,405 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:47:54,410 _handle_stage_init line:125 parse_header_success domain dst:chromefeedcontentsuggestions-pa.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:47:54,754 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:47:54,761 _handle_stage_init line:125 parse_header_success domain dst:www.google.com:443
aioshadowsocks | [WARNING]2021-01-18 03:47:55,577 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: clientservices.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:47:56,719 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: content-autofill.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:47:56,725 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: growth-pa.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:47:57,577 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:47:57,581 _handle_stage_init line:125 parse_header_success domain dst:growth-pa.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:47:58,283 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:47:58,286 _handle_stage_init line:125 parse_header_success domain dst:content-autofill.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:47:59,069 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:47:59,073 _handle_stage_init line:125 parse_header_success domain dst:www.google.com:443
aioshadowsocks | [INFO]2021-01-18 03:47:59,393 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:47:59,398 _handle_stage_init line:125 parse_header_success domain dst:clientservices.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:47:59,411 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: chromefeedcontentsuggestions-pa.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:47:59,763 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: www.google.com:443
aioshadowsocks | [INFO]2021-01-18 03:47:59,946 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:47:59,953 _handle_stage_init line:125 parse_header_success domain dst:chromefeedcontentsuggestions-pa.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:00,247 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:00,251 _handle_stage_init line:125 parse_header_success domain dst:www.google.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:02,586 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: growth-pa.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:03,291 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: content-autofill.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:03,774 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:03,779 _handle_stage_init line:125 parse_header_success domain dst:www.google.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:03,788 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:03,795 _handle_stage_init line:125 parse_header_success domain dst:content-autofill.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:04,076 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: www.google.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:04,401 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: clientservices.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:04,539 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:04,545 _handle_stage_init line:125 parse_header_success domain dst:clients1.google.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:04,564 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:04,568 _handle_stage_init line:125 parse_header_success domain dst:www.google.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:04,911 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:04,915 _handle_stage_init line:125 parse_header_success domain dst:clientservices.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:04,956 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: chromefeedcontentsuggestions-pa.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:05,253 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: www.google.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:05,601 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:05,606 _handle_stage_init line:125 parse_header_success domain dst:play.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:05,630 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:05,633 _handle_stage_init line:125 parse_header_success domain dst:www.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:08,784 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: www.google.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:08,798 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: content-autofill.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:09,329 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:09,333 _handle_stage_init line:125 parse_header_success domain dst:www.google.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:09,549 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: clients1.google.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:09,570 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: www.google.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:09,918 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: clientservices.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:10,161 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:10,166 _handle_stage_init line:125 parse_header_success domain dst:clients1.google.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:10,609 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: play.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:10,636 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: www.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:10,701 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:10,705 _handle_stage_init line:125 parse_header_success domain dst:content-autofill.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:11,174 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:11,175 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:11,180 _handle_stage_init line:125 parse_header_success domain dst:play.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:11,185 _handle_stage_init line:125 parse_header_success domain dst:www.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:14,339 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: www.google.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:14,882 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:14,887 _handle_stage_init line:125 parse_header_success domain dst:www.google.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:15,169 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: clients1.google.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:15,708 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: content-autofill.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:16,185 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: play.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:16,189 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: www.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:16,194 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:16,202 _handle_stage_init line:125 parse_header_success domain dst:content-autofill.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:19,892 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: www.google.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:20,393 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:20,399 _handle_stage_init line:125 parse_header_success domain dst:www.google.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:21,205 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: content-autofill.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:25,405 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: www.google.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:25,982 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:25,986 _handle_stage_init line:125 parse_header_success domain dst:www.google.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:30,992 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: www.google.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:31,487 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:31,492 _handle_stage_init line:125 parse_header_success domain dst:www.google.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:36,494 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: www.google.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:37,162 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:37,168 _handle_stage_init line:125 parse_header_success domain dst:www.google.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:42,176 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: www.google.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:42,699 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:42,704 _handle_stage_init line:125 parse_header_success domain dst:www.google.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:44,965 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:44,969 _handle_stage_init line:125 parse_header_success domain dst:update.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:47,710 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: www.google.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:49,974 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: update.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:50,488 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:50,492 _handle_stage_init line:125 parse_header_success domain dst:update.googleapis.com:443
aioshadowsocks | [WARNING]2021-01-18 03:48:55,500 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: update.googleapis.com:443
aioshadowsocks | [INFO]2021-01-18 03:48:56,036 _init_transport line:53 connection_made: 223.91.62.251,tcp
aioshadowsocks | [INFO]2021-01-18 03:48:56,041 _handle_stage_init line:125 parse_header_success domain dst:update.googleapis.com:80
aioshadowsocks | [WARNING]2021-01-18 03:49:01,049 _handle_stage_init line:142 connection failed, <class 'asyncio.exceptions.TimeoutError'> e: update.googleapis.com:80

`
**好像还是不可以.....**
![image](https://user-images.githubusercontent.com/49980280/104870366-506f6e80-5983-11eb-94e9-6269f1ee5918.png)

**Comment by yscxyjd** [comment]
![image](https://user-images.githubusercontent.com/49980280/104870651-ffac4580-5983-11eb-8e1b-66493685e94b.png)

**Comment by yscxyjd** [comment]
是没有配置ssl的问题？
手机上这样显示
![image](https://user-images.githubusercontent.com/49980280/104870780-469a3b00-5984-11eb-928e-55a7394c8bef.png)

**Comment by yscxyjd** [comment]
@Ehco1996 有没有解决方案，只有我的是这样吗，不应该啊

**Comment by Ehco1996** [comment]
@yscxyjd  那应该就是机器的原因，建议换台机器试试
或者环一下你这台机器的dns server到8.8.8.8

**Comment by Ehco1996** [comment]
不能。


建议在服务器上直接 dig一下 `update.googleapis.com:80`
然后看看返回的ip是啥，然在ping一下看看

或者直接curl一下试试看是不是通的

**Comment by yscxyjd** [comment]
`[root@hwsrv-825895 shadowsocks-manager]# dig update.googleapis.com:80

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.3 <<>> update.googleapis.com:80
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 43831
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;update.googleapis.com:80.      IN      A

;; AUTHORITY SECTION:
.                       86371   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2021011800 1800 900 604800 86400

;; Query time: 7 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: 一 1月 18 09:37:48 UTC 2021
;; MSG SIZE  rcvd: 128

[root@hwsrv-825895 shadowsocks-manager]# 
`

**Comment by yscxyjd** [comment]
我也看不懂啊

**Comment by Ehco1996** [comment]
有新的发现吗？

**Comment by yscxyjd** [comment]
不搞了，换成v2了，这个有点费脑筋/苦笑
