### ISSUE TITLE
关于节点的默认udp转发状态？

### ISSUE THREAD

**Issue by maker2002** [Ehco1996/aioshadowsocks#144]
使用aioshadowsocks创建的节点无法正常使用clubhouse，具体表现为进入房间后无法收发语音；是不是默认情况节点的UDP转发没开？感觉可能与UDP有关。
测试了下，在客户端关闭udp转发就正常了，请问下如何配置开启udp转发？

另外看到这个https://github.com/Ehco1996/django-sspanel/issues/470
是不是就是我说的这个功能？希望能早点看到实现。

**Comment by Ehco1996** [comment]
默认udp转发是打开的，不能的话可能哪里有问题

可以提供一下客户端和服务端的日志，我研究一下

**Comment by maker2002** [comment]
> 可以提供一下客户端和服务端的日志，我研究一下

请问如何打印服务端日志？

**Comment by Ehco1996** [comment]
> > 可以提供一下客户端和服务端的日志，我研究一下
> 
> 在客户端中能看到udp超时的日志：
> `[22:32:30.128] udp socket close reason => udp timeout error, timeout:5.000000, elapsed:6.301785`
> 
> 请问如何打印服务端日志？
> 
> edit:
> 刚刚在一台debian10的服务器上部署了节点，udp转发正常了，之前的测试2台udp转发不正常的都是centos8的服务器，可能和centos的系统有关系？
> 
> edit2:
> 刚刚简单测试了下把centos的selinux和firewalld.service关闭，没有效果。

那看上去就是机器配置的原因

服务端的日志可以在控制台看，如果用docker部署的话可以用 docker logs 命令看

**Comment by maker2002** [comment]
> > > 可以提供一下客户端和服务端的日志，我研究一下
> > 
> > 
> > 在客户端中能看到udp超时的日志：
> > `[22:32:30.128] udp socket close reason => udp timeout error, timeout:5.000000, elapsed:6.301785`
> > 请问如何打印服务端日志？
> > edit:
> > 刚刚在一台debian10的服务器上部署了节点，udp转发正常了，之前的测试2台udp转发不正常的都是centos8的服务器，可能和centos的系统有关系？
> > edit2:
> > 刚刚简单测试了下把centos的selinux和firewalld.service关闭，没有效果。
> 
> 那看上去就是机器配置的原因
> 
> 服务端的日志可以在控制台看，如果用docker部署的话可以用 docker logs 命令看

服务端能看到这样的日志：
`[WARNING]2021-02-27 22:39:33,287 handle_data_received line:93 decrypt data error:can not find enable access user: 443-2-<class 'shadowsocks.ciphers.CHACHA20IETFPOLY1305'> remote:('65.49.20.67', 60347),type:udp closing...`

**Comment by Ehco1996** [comment]
> > > > 可以提供一下客户端和服务端的日志，我研究一下
> > > 
> > > 
> > > 在客户端中能看到udp超时的日志：
> > > `[22:32:30.128] udp socket close reason => udp timeout error, timeout:5.000000, elapsed:6.301785`
> > > 请问如何打印服务端日志？
> > > edit:
> > > 刚刚在一台debian10的服务器上部署了节点，udp转发正常了，之前的测试2台udp转发不正常的都是centos8的服务器，可能和centos的系统有关系？
> > > edit2:
> > > 刚刚简单测试了下把centos的selinux和firewalld.service关闭，没有效果。
> > 
> > 
> > 那看上去就是机器配置的原因
> > 服务端的日志可以在控制台看，如果用docker部署的话可以用 docker logs 命令看
> 
> 服务端能看到这样的日志：
> `[WARNING]2021-02-27 22:39:33,287 handle_data_received line:93 decrypt data error:can not find enable access user: 443-2-<class 'shadowsocks.ciphers.CHACHA20IETFPOLY1305'> remote:('65.49.20.67', 60347),type:udp closing...`

这个报错是因为上来的udp包不对，你确定换了系统之后就能用么？

**Comment by maker2002** [comment]
> > > > > 可以提供一下客户端和服务端的日志，我研究一下
> > > > 
> > > > 
> > > > 在客户端中能看到udp超时的日志：
> > > > `[22:32:30.128] udp socket close reason => udp timeout error, timeout:5.000000, elapsed:6.301785`
> > > > 请问如何打印服务端日志？
> > > > edit:
> > > > 刚刚在一台debian10的服务器上部署了节点，udp转发正常了，之前的测试2台udp转发不正常的都是centos8的服务器，可能和centos的系统有关系？
> > > > edit2:
> > > > 刚刚简单测试了下把centos的selinux和firewalld.service关闭，没有效果。
> > > 
> > > 
> > > 那看上去就是机器配置的原因
> > > 服务端的日志可以在控制台看，如果用docker部署的话可以用 docker logs 命令看
> > 
> > 
> > 服务端能看到这样的日志：
> > `[WARNING]2021-02-27 22:39:33,287 handle_data_received line:93 decrypt data error:can not find enable access user: 443-2-<class 'shadowsocks.ciphers.CHACHA20IETFPOLY1305'> remote:('65.49.20.67', 60347),type:udp closing...`
> 
> 这个报错是因为上来的udp包不对，你确定换了系统之后就能用么？

换了系统后用shadowrocket开启UDP转发可以用clubhouse，但使用ouline客户端（默认开启UDP转发）无法正常使用clubhouse。但debian系统下没有udp的报错，都是正常的日志
`[INFO]2021-02-28 10:54:56,697 _handle_stage_init line:124 parse_header_success atype: udp ipv4 from: 1.1.1.1 dst: 52.58.56.244:8443`

**Comment by Ehco1996** [comment]
那看上去有可能是客户端的问题？

**Comment by maker2002** [comment]
> 那看上去有可能是客户端的问题？

今天用之前centos8的系统从新安装了debian10的系统，使用outline客户端链接后，前几秒钟有声音，然后就没有了。docker logs也没看到udp报错的日志。

感觉是aioss服务端和outline的配合问题？
总体感觉是aioss的udp转发似乎有点问题，是否方便远程或者其他方式debug？

**Comment by Ehco1996** [comment]
@maker2002 ,最新版本对udp的行为做了一些优化，可以试试看
