### ISSUE TITLE
【讨论】去除 gRPC 改用 rpc.py

### ISSUE THREAD

**Issue by abersheeran** [Ehco1996/aioshadowsocks#195]
因为工作原因前段时间也用了 gRPC，感觉在 Python3 里很不好用，各种问题。然后自己写了一个 RPC 框架代替 gRPC 在 Python3 里用。看了一眼你的依赖，里面有 httpx，改用 rpc.py 也不会额外增加大量依赖。https://github.com/abersheeran/rpc.py

这个 issue 可以当作是推广，毕竟我确实发自己项目了。但更多是看了你的源代码，感觉 aioshadowsocks 的 gRPC 部分太冗余、繁琐了。

如有冒犯，可删除此 Issue。

**Comment by Ehco1996** [comment]
gRPC 的好处是可以跨语言通信，另外你说 gRPC 部分的代码太冗余，请问是哪一部分你觉得冗余呢？

**Comment by abersheeran** [comment]
https://github.com/Ehco1996/aioshadowsocks/blob/master/shadowsocks/services.py#L47 代码不断重复

**Comment by abersheeran** [comment]
> gRPC 的好处是可以跨语言通信

只要支持 HTTP，都可以跨语言，这个不是问题。rpc.py 可以用 JSON 序列化器，而且不强求 HTTP2，跨语言比 gRPC 强依赖 HTTP2 和 protobuf 应该要强。

而且……你这个接口真的有跨语言需求吗？我看都是 Python3 的.

**Comment by Ehco1996** [comment]
@abersheeran 

1)   我不觉得你指出的代码有重复冗余的地方
2）不是底层的协议是通用的就可以说自己的框架是跨语言的，如果按照这样的说法，所有的框架都是跨语言的，都是跑在 IP 协议上的
3） gRPC 当然支持 json 序列化，并且他有很强大的社区，你几乎可以找到所有你需要的插件中间件
4） PB 的设计和实现的确是坨屎

最后，我这里实现的只是服务端，客户端想调用这些接口的话不需要语言层面上的支持，哪怕用 postman 都可以调用

**Comment by abersheeran** [comment]
好的。
