### ISSUE TITLE
CentOS 7 安装失败

### ISSUE THREAD

**Issue by frankniubi** [Ehco1996/aioshadowsocks#265]
ERROR: Could not find a version that satisfies the requirement aioshadowsocks (from versions: none)

自编译安装Python 3.10.4 / 自带Python 2.7.5; pip3 22.0.4

**Comment by Ehco1996** [comment]
可以根据 dockerfile 里的脚本研究一下如何安装

**Comment by frankniubi** [comment]
解决了 居然是python没带ssl= =
