### ISSUE TITLE
aioss run_ss_server 启动错误

### ISSUE THREAD

**Issue by kitcoun** [Ehco1996/aioshadowsocks#268]
root@123:/usr# aioss run_ss_server
正在创建<Model: User>内存数据库
Start grpc Server on 127.0.0.1:5000
flush_metrics_to_remote error: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
sync error: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
flush_metrics_to_remote error: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
sync error: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
flush_metrics_to_remote error: [Errno 104] Connection reset by peer

**Comment by Ehco1996** [comment]
aioss 需要配合 https://github.com/Ehco1996/django-sspanel 这个使用，具体可以看一下文档

**Comment by kitcoun** [comment]
> aioss 需要配合 [https://github.com/Ehco1996/django-sspanel ](https://github.com/Ehco1996/django-sspanel) 这个使用，具体可以看一下文档

没有做加密吗？ip都是瞬间被墙
