### ISSUE TITLE
这个目前同时支持ss/ssr吗？

### ISSUE THREAD

**Issue by perfect-network** [Ehco1996/aioshadowsocks#3]
还有就是目前支持那些东西了，有API开放了吗？如果我拿来做panel的后端，功能都能实现了吗？API完善了吗...😂😂😂

**Comment by perfect-network** [comment]
...我拉到本地测试过...ss测试链接成功了....但是貌似ssr不支持吧？

**Comment by Ehco1996** [comment]
不支持ssr
