### ISSUE TITLE
aioshadowsocks对接出现问题

### ISSUE THREAD

**Issue by cloudfreecn** [Ehco1996/aioshadowsocks#6]
![QQ截图20190923073057.png](https://i.loli.net/2019/09/23/PVgrWKBHxXELjaz.png)
![QQ截图20190923073107.png](https://i.loli.net/2019/09/23/hUgpqfjRXlGcs2u.png)

作者大大这个是在那块出问题了

现在的Django-sspanel不支持这个shadowsocksr-deprecated分支后端了吗

很久没搞了   感觉变化很大。

**Comment by LifeVictory** [comment]
前端节点显示在线的 但是无法上网。

**Comment by Ehco1996** [comment]
这个需要Python3.7以上的版本
 建议直接用docker起 会方便很多

**Comment by LifeVictory** [comment]
所以是旧的后端不能用在现在的前端了是吧

**Comment by Ehco1996** [comment]
是的
