### ISSUE TITLE
带宽占用问题

### ISSUE THREAD

**Issue by 1420125167** [Ehco1996/aioshadowsocks#70]
在没有人使用节点的情况下会出现高带宽占用的问题，软件会把整个服务器的下行带宽占满，直到手动kill才会停止
![QQ图片20200816170214](https://user-images.githubusercontent.com/13842432/90330836-6c40a400-dfe2-11ea-902f-919db742346b.png)

**Comment by 1420125167** [comment]
现在怀疑是IDM的锅，在IDM多线程下载结束后服务端依然会保持高下载带宽（从别的服务器下载到ss服务器），但是没有上传（从ss服务器到本地）
单线程下载不受影响
![QQ截图20200816174609](https://user-images.githubusercontent.com/13842432/90331599-61890d80-dfe8-11ea-84a1-254069a03421.jpg)

**Comment by Ehco1996** [comment]
@1420125167  可以用工具查一下机器上的链接，

**Comment by 1420125167** [comment]
> @1420125167 可以用工具查一下机器上的链接，

是python高占用，而且网站后台把跑的流量都算到我头上去了

**Comment by Ehco1996** [comment]
> > @1420125167 可以用工具查一下机器上的链接，
> 
> 是python高占用，而且网站后台把跑的流量都算到我头上去了

可以把机器上的链接信息贴上来看看

**Comment by 1420125167** [comment]
显示连接最多的是到我个人电脑（39.xxx.xxx.xxx）
![连接](https://user-images.githubusercontent.com/13842432/90653666-09fdd280-e272-11ea-8ddd-dd761a405dcd.jpg)

**Comment by 1420125167** [comment]
172开头的是服务器地址
![QQ截图20200819231814](https://user-images.githubusercontent.com/13842432/90653868-4cbfaa80-e272-11ea-9c29-f155ee40dc04.jpg)

**Comment by Ehco1996** [comment]
> 显示连接最多的是到我个人电脑（39.xxx.xxx.xxx）
> ![连接](https://user-images.githubusercontent.com/13842432/90653666-09fdd280-e272-11ea-8ddd-dd761a405dcd.jpg)

看上去是你电脑的客户端没把链接断开导致的。你把客户端关掉这个链接应该就断了

**Comment by 1420125167** [comment]
> > 显示连接最多的是到我个人电脑（39.xxx.xxx.xxx）
> > ![连接](https://user-images.githubusercontent.com/13842432/90653666-09fdd280-e272-11ea-8ddd-dd761a405dcd.jpg)
> 
> 看上去是你电脑的客户端没把链接断开导致的。你把客户端关掉这个链接应该就断了

刚试了一下，并不会

**Comment by Ehco1996** [comment]
@1420125167  我有去看了一下，的确是会有链接不释放的问题， 我修一下

**Comment by 1420125167** [comment]
> ```
> * 找到pid
> 
> ps -ef | grep ehco
> 
> 查看链接数
> 
> lsof -p 4721 -nP | grep TCP
> ```
> 
> @1420125167 我有又看了一下，的确是会有链接不释放的问题， 我修一下

![QQ截图20200902111259](https://user-images.githubusercontent.com/13842432/91927906-4703a380-ed0d-11ea-8f82-89de1765f79d.jpg)
到个人电脑和谷歌云的连接都没断开

**Comment by Ehco1996** [comment]
@1420125167  最新版本已经修掉啦
