### ISSUE TITLE
大佬能不能写个详细的Docker安装教程

### ISSUE THREAD

**Issue by changwangyun** [Ehco1996/aioshadowsocks#8]
大佬能不能写个详细的Docker安装教程
看了一晚上Docker入门  迷茫

**Comment by Ehco1996** [comment]
readme里不是有一键安装脚本么

**Comment by changwangyun** [comment]
嗯 但是不知道怎么跟前端对接啊。。。。
Pulling ss (ehco1996/aioshadowsocks:runtime)...
runtime: Pulling from ehco1996/aioshadowsocks
e7c96db7181b: Pull complete
799a5534f213: Pull complete
913b50bbe755: Pull complete
11154abc6081: Pull complete
c805e63f69fe: Pull complete
93eaff4e0404: Pull complete
b06642b6dde3: Pull complete
Creating aioshadowsocks ... done
Attaching to aioshadowsocks
aioshadowsocks | [INFO]2019-10-07 15:02:15,706-root - _init_memory_db() - 正在创建<Model: User>内存数据库
aioshadowsocks | [INFO]2019-10-07 15:02:15,707-root - _init_memory_db() - 正在创建<Model: UserServer>内存数据库
aioshadowsocks | [INFO]2019-10-07 15:02:15,851-root - start_grpc_server() - Start Grpc Server on 127.0.0.1:5000
aioshadowsocks | [INFO]2019-10-07 15:02:15,853-root - init_server() - user:1 method:aes-256-cfb password:hellotheworld port:2345 已启动
aioshadowsocks | [INFO]2019-10-07 15:02:15,853-root - init_server() - user:2 method:none password:hellotheworld port:2346 已启动

**Comment by Ehco1996** [comment]
改一下docker-compose.yml 里的环境变量
SS_API_ENDPOINT
改成面板后台里节点对应的
