### ISSUE TITLE
搭建教程说明问题

### ISSUE THREAD

**Issue by LunacyZeus** [Ehco1996/aioshadowsocks#9]
今天跟着教程搭建。。。然后发现教程里那个后端地址直接填网址貌似对接不了。。。。然后折腾了半天，看了下源代码。。。完整地址应该是这个
http://网址域名/api/user_ss_config/1/?token=youowntoken

第一次用这个.....不怎么熟悉，终于折腾出来了

**Comment by jackjieYYY** [comment]
http://domain.com/api/user_ss_config/nodeID/?token=youowntoken
http://domain.com/api/user_vmess_config/nodeID/?token=youowntoken
